version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mousstass_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moustass_web
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: mousstass_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=moustass_web
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: mousstass_frontend
    restart: always
    expose:
      - "80"
    depends_on:
      - backend

  apache:
    image: httpd:2.4
    container_name: mousstass_apache
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/config:/usr/local/apache2/conf
      - ./apache/logs:/usr/local/apache2/logs
      - ./frontend/public:/usr/local/apache2/htdocs
      - ./apache/ssl:/usr/local/apache2/ssl
    depends_on:
      - frontend

volumes:
  mysql_data:
